version: '3.7'
services:
    game-server:
        build:
            context: ./images/debian-buster
#            network: host
        volumes:
            - ../project:/project
        ports:
            - 8080:8080
            - 9222:9222
            - "9001-9010:9001-9010/udp"
        working_dir: /project
        command: tail -f /dev/null
#        network_mode: "host"
        networks:
            vpcbr:
                ipv4_address: ${DEV_CONTAINER_IP}
networks:
    vpcbr:
        driver: bridge
        ipam:
            config:
                - subnet: ${DEV_CONTAINER_SUBNET}
